import { MantineProvider } from "@mantine/core"
import { Inter } from "next/font/google"
import Head from "next/head"

import { FilledButton } from "@/shared/ui/buttons"

const inter = Inter({ subsets: ["latin"] })

const HomePage = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={inter.className}>
				<MantineProvider>
					<h1>HomePage</h1>
					<FilledButton>test</FilledButton>
				</MantineProvider>
			</main>
		</>
	)
}

export default HomePage
